version: "3.9"

services:
  range_viewer_react:
    build: 
      context: .
      dockerfile: ./docker/local/Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    image: packerson/range_viewer_react
    container_name: react_container
    working_dir: /app
    command: npm start
